projet/appli/urls.py
from django.urls import path, re_path
from . import views

app_name = 'appli'

urlpatterns = [
    re_path(r'^citations/$', views.citations, name='citations'),
    re_path(r'^citez/$', views.citez, name='citez'),
    re_path(r'^apropos/$', views.apropos, name='apropos'),
]

projet/projet/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.conf import settings
from appli import views

#---- activation en prod ------------
from django.views.static import serve
#-----------------------------------



urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(r'^$', views.index, name='index'),
    re_path(r'^appli/', include('appli.urls', namespace='appli')),

#---- activation en prod pour servir fichiers STATIC ------------
#---- en dév (serveur local Django) quand DEBUG=False -----------
#---- et lancer ./manage.py runserver --insecure ----------------
   re_path(r'^static/(?P<path>.*)$', serve,{'document_root':settings.STATIC_ROOT}),
#-----------------------------------

]


if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
            re_path(r'^__debug__/', include(debug_toolbar.urls)),
            ] + urlpatterns

projet/appli/models.py
from django.db import models
from django.utils.text import Truncator

class Quote(models.Model):
    texte = models.TextField()
    auteur = models.CharField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='date de parution')

    class Meta:
        verbose_name = "citation"

    def __str__(self):
        return Truncator(self.texte).chars(20, truncate='...')

projet/appli/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from .models import Quote


# Alternative avec Form:
#class QuoteForm(forms.Form):
#    texte = forms.CharField(widget=forms.Textarea)
#    auteur = forms.CharField()
#
#
# Avec ModelForm:
class QuoteForm(ModelForm):
    class Meta:
        model = Quote
        fields = ["texte", "auteur"]
        widget = {
                'texte': TextInput(attrs={'class': 'form-control'}),
                'auteur': TextInput(attrs={'class': 'form-control'}),
                }

projet/appli/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .models import Quote
from .forms import QuoteForm


def index(request):
    quotes = Quote.objects.order_by('-created_at')[:1]
    context = {'quotes': quotes}
    return render(request, 'appli/index.html', context)

def citations(request):
    quotes_list = Quote.objects.order_by('-created_at')
    # pagination avec url de type : appli/citations/?page=1
    paginator = Paginator(quotes_list, 5) # création de l'instance avec nombre de quotes par page 
    page = request.GET.get('page') # récupération du n°de la page courante de l'url /?page=3
    try:
        quotes = paginator.page(page) # groupe de quotes 
    except PageNotAnInteger:
        # si page n'est pas entier , on délivre la 1ère page:
        quotes = paginator.page(1)
    except EmptyPage:
        # si page out of range, on délivre la dernière page:
        quotes = paginator.page(paginator.num_pages)

    context = {
            'quotes': quotes,
            'paginate': True
            } 
    return render(request, 'appli/citations.html', context)

def citez(request):
    quotes = Quote.objects.order_by('-created_at')[:3]
    context = {'quotes': quotes}
    form = QuoteForm(request.POST or None)
    if form.is_valid():
        texte = form.cleaned_data["texte"]
        auteur = form.cleaned_data["auteur"]
        # attention : la méthode cleaned_data ne fonctionne qu'après
        # avoir appliqué la méthode is_valid

        new_quote = Quote.objects.create(
                texte=texte,
               auteur=auteur,
                )
        new_quote.save()
        context['new_quote'] = new_quote

        return render(request, 'appli/merci.html', context)

    context['form'] = form
    return render(request, 'appli/citez.html', context)

def apropos(request):
    # a supprimer??? - pas la peine de faire une vue pour ça ???
    return render(request, 'appli/apropos.html')

projet/appli/templates/appli/apropos.html
{% extends 'appli/base.html' %}

{% block content %}
    <section class="intro">
        <h2> A propos de ce site : </h2>
        <p> ce site est un test.</p>
    </section>
    <section class="listing">
    </section>
{% endblock %}

projet/appli/templates/appli/base.html
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta name="viewport" content="width=device-width" />
        <meta charset="utf-8" />
        {% load static %}
        <!-- css -->
        <link rel="stylesheet" href="{% static 'appli/css/style.css' %}" />
        <!-- <link rel="stylesheet" href="../../static/appli/css/style.css" /> -->
        <title>Site Test</title>
    </head>
    <body>
        <div id="bloc-page">    
            <header>
                <div id=entete>
                    <figure>
                        <img src="{%static 'appli/img/rose.jpg' %}" alt="Une rose rouge" />
                    </figure>
                    <div class="titre">
                        <h1>
                            <a href="{% url 'index' %}">Arroudennad</a>
                        </h1>
                        <h2>Le site qui cite</h2>
                    </div>
                </div>

                <ul class="navbar">
                    <li><a href="{% url 'index' %}" class="bouton_menu">Accueil</a></li>
                    <li><a href="{% url 'appli:citations' %}" class="bouton_menu">Les citations</a></li>
                    <li><a href="{% url 'appli:apropos' %}" class="bouton_menu">A propos</a></li>
                </ul>
    
            </header>
            <main>
                {% block content %}{% endblock %}
            </main>
            <footer>
                Site expérimental mais génial.
            </footer>
    
        </div>
    </body>
</html>

projet/appli/templates/appli/citations.html
{% extends 'appli/base.html' %}

{% block content %}

    <section class="intro">
        <h2> </h2>
    </section>
    <section class="cta">
        <a href="{% url 'appli:citez' %}" class="bouton_citer">Ecrivez une nouvelle citation !</a>
    </section>
    <section class="listing">
        {% include 'appli/list.html' with list_title='Toutes les citations :' %}
    </section>
{% endblock %}

projet/appli/templates/appli/citez.html
{% extends 'appli/base.html' %}

{% block content %}
    <section class="intro">
        <h2> Ecrivez une nouvelle citation et entrez dans la légende ! </h2>
    </section>
    <section class="formulaire">
        <form action="{% url 'appli:citez' %}" method="post">
            {% csrf_token %}
            <div>
                <label for="{{ form.texte.id_for_label }}" class="control-label">Ecrivez votre citation ici ...</label>
            </div>
            <div class:control-box>
                {{ form.texte }}
            </div>
            <div>
                <label for="{{ form.auteur.id_for_label }}" class="control-label">Votre nom ou pseudo:</label>
            </div>
            <div class:control-box>
                {{ form.auteur }}
            </div>
            <button type="submit" class="bouton_valid">Envoyer</button>
            
        </form>
    </section>

    <section class="listing">
        {% include 'appli/list.html' with list_title='Les dernières citations :' %}
    </section>
{% endblock %}

projet/appli/templates/appli/citez_test.html
{% extends 'appli/base.html' %}

{% block content %}
<!-- autres possibilités pour les formulaires (fichier inactif) : -->
<p>==============================</p>
<!-- avec du html classique : -->
<form action="/appli/citez/" method="post">
    {% csrf_token %}
    <p>
        <label for="id-texte">Votre citation :</label>
        <textarea name="texte" id="id-texte" rows=5 cols=50 placeholder="Homme libre, toujours tu chériras la mer !"></textarea>
    </p>
    <p>
        <label for="id-auteur">Votre nom ou pseudo:</label>
        <input type="text" name="auteur" id="id-auteur" placeholder="Charles Baudelaire"/>
    </p>
    <input type="submit" value ="Envoyer"/>

</form>

<p>==============================</p>
<!-- en utilisant la méthode .as_p de django -->
<form action="/appli/citez/" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value ="Envoyer"/>

</form>
{% include 'appli/list.html' with list_title='Les dernières citations :' %}
{% endblock %}

projet/appli/templates/appli/index.html
{% extends 'appli/base.html' %}

{% block content %}
    <section class="intro">
        <h2> Tout ce qui est écrit continue de vivre ; tout ce qui n'est que parler meurt.  </h2>
    </section>
    <section class="cta">
        <a href="{% url 'appli:citez' %}" class="bouton_citer"  target="_blank">Ecrivez votre pensée !</a>
    </section>
    <section class="listing">
        {% include 'appli/list.html' with list_title='La dernière citation :' %}
    </section>
{% endblock %}

projet/appli/templates/appli/list.html
<div class="intro">
    <h2>{{list_title}}</h2>
</div>

<div class="list-citations">
{% for quote in quotes %}

<div class="citation">

    <p>"{{quote.texte}}"</p>
    <p ALIGN="right">{{quote.auteur}}, le {{quote.created_at}}</p>
</div>
    
{% endfor %}
</div>

{% if paginate %}
    <div class="pagination">
        {% if quotes.has_previous %}
           <a href='?page={{ quotes.previous_page_number }}' class="bouton_page">Page précédente</a>
        {% endif %}
        {% if quotes.has_next %}
           <a href='?page={{ quotes.next_page_number }}' class="bouton_page">Page suivante</a>
        {% endif %}
    </div>
{% endif %}

projet/appli/templates/appli/merci.html
{% extends 'appli/base.html' %}

{% block content %}
    <section class="intro">
        <h2>Merci {{ new_quote.auteur }} ! Votre citation a bien été enregistrée !</h2>
    </section>
    <section class="listing">
        {% include 'appli/list.html' with list_title='Les dernières citations :' %}
    </section>
{% endblock %}

projet/appli/templates/appli/merci_test.html
{% extends 'appli/base.html' %}

{% block content %}
<h1>Merci ! Votre citation a bien été enregistrée !</h1>
</br>
{% include 'appli/list.html' with list_title='Les dernières citations :' %}
{% endblock %}